kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.27.0
  extraPortMappings:
  # used to query webhook NodePort
  - containerPort: 30100
    hostPort: 30100
    protocol: TCP
