# permissions for end users to edit nginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nginx-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo-operator
    app.kubernetes.io/part-of: demo-operator
    app.kubernetes.io/managed-by: kustomize
  name: nginx-editor-role
rules:
- apiGroups:
  - webserver.demo.local
  resources:
  - nginxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webserver.demo.local
  resources:
  - nginxes/status
  verbs:
  - get
