apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: demo-webhook.demo.local
webhooks:
  - name: demo-webhook.demo.local
    namespaceSelector:
      matchLabels:
        demo-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: demo-webhook
        path: /validate
        port: 443
      caBundle: |-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lVVFVxV0cxM2hxeG90c3cyUHNOQTNyV0p1bFJrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pERUxNQWtHQTFVRUJoTUNWVUV4RlRBVEJnTlZCQU1NREdSbGJXOHRkMlZpYUc5dmF6QWVGdzB5TXpBMwpNRGN5TVRJMU1EVmFGdzB5TkRBM01EWXlNVEkxTURWYU1DUXhDekFKQmdOVkJBWVRBbFZCTVJVd0V3WURWUVFECkRBeGtaVzF2TFhkbFltaHZiMnN3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREYKclZDR2RNclRGanJYOUVONERhaTl4KzZEa1l6SmQzYlBTc1l6dzdvbUducS8zNzUxRG1OWFBibU5kaWVPWkRzSQp6QnhZSFFmY1doL2hHd29oeGhXcWVETWEvUDFQdnYyYkx2R1FvZk82UnZjM2ZIR0dJRTFJZXJNMnNtUUh0dXlOCjU0ak5seExWVExla04rRFkxQVRhVjFhNVdWMVNDNXEra3FkOG43VEZxN2lBMUt4c3dFOUtHWCtkcHZ2anVHaU8KV3dROWFXSklHaHkyWjhNQVhRdS9QK29wcVZ0RWtPclVFc0Jod0tNZDZYb3BoRDBobS96R1J0c1JrdWs2NlVrMQpKOGwvdVBBOHlFMDV0TkJjR0VzVEViWWwwcitpVmxybEszQmVBNklTYzdKZ0k4ZldEWTRpeGJWTkF3V3I2QU9SCkdlQVhUQmVXcjJ4cXpnNnVMQkpYQWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJRenFWWlpUQnFTTjZNeGMvb0UKQi9VUjJzQkI0akFmQmdOVkhTTUVHREFXZ0JRenFWWlpUQnFTTjZNeGMvb0VCL1VSMnNCQjRqQVBCZ05WSFJNQgpBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUF6YlRacWNxVG1VWGYxWW9RT2ovZUpzK1NECkwyaWVHbXlzNHhtMlB5ZEY5RzV5Tk5oVmthczEyQ0dnWEZFZEtEbDRjUEVMRXJqNzFHNXlhc2VRbnI5V3lIbloKLzFrL1FtWHA4TkVEbGhTaER2N2t2RXUrNGN2dnR0b3duNTNsSmRqRWhaa0FFeHlGRmVsM0YyMXdxWmkvdlVFdQpGbElyWG1CY1RTSEpROThaanF2Y2xnbWw4VnRZQ1YzZXNrUjAxQ0RVQzNiM2p4UDMwV25VaXZkcUthc1VueFB5CnNYZWRIWHM0RDJLS1RSTitoSENFTHVUTHkya1JOY2ZNbnJqaW5rMUt2elVsQW9QQ3RtYk1CVFNjY2hzekFvYmUKam9Gc2VNNVlEdUxsVjQ2YldYS1k3bnNzbnlFZHNoQWhPWjk5bG1BZkNrR21ncTFLcVp3T3lQODBFVjBrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
